spring:
  application:
    name: aulaspringsouza2JPA

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    # Define se o hibernate deve criar/atualizar as tabelas automaticamente
    hibernate:
      ddl-auto: update

    # Mostra o SQL no console (Padrão Spring)
    show-sql: true

    properties:
      hibernate:
        # Formata o SQL para ficar legível
        format_sql: true
        # Opcional: O Spring Boot 3+ detecta o Dialect automaticamente,
        # mas você pode manter se preferir ser explícito.
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configura o nível de log para ver parâmetros passados nas queries (opcional)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE